apiVersion: v1
kind: Secret
metadata:
  name: clusternet-agent-cluster-registration
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  parentURL: {{ required ".Values.parentURL is required!" .Values.parentURL }}
  regToken: {{ required ".Values.registrationToken is required!" .Values.registrationToken }}
