---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "clusternet-syncer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4}}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
  name: clusternet-syncer-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: clusternet-syncer-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - apps.clusternet.io
  resources:
  - bases
  - descriptions
  - helmcharts
  - manifests
  - subscriptions
  verbs:
  - '*'
- apiGroups:
  - clusters.clusternet.io
  resources:
  - clusterregistrationrequests
  - managedclusters
  verbs:
  - '*'
- apiGroups:
  - clusters.clusternet.io
  resources:
  - managedclusters/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - shadow
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: clusternet-syncer-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clusternet-syncer-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "clusternet-syncer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: clusternet-syncer-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusternet-syncer-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "clusternet-syncer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
